//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaseronBul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirim
    {
        public int BildirimId { get; set; }
        public Nullable<int> KabulId { get; set; }
        public string FirmaAciklama { get; set; }
        public string UyeAciklama { get; set; }
        public Nullable<bool> FDurum { get; set; }
        public Nullable<bool> BDurum { get; set; }
    
        public virtual KabulEdilen KabulEdilen { get; set; }
    }
}
