//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaseronBul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaTeklif
    {
        public FirmaTeklif()
        {
            this.KabulEdilens = new HashSet<KabulEdilen>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IlanNo { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<double> Fiyat { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual Ilan Ilan { get; set; }
        public virtual ICollection<KabulEdilen> KabulEdilens { get; set; }
    }
}
