//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaseronBul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public Firma()
        {
            this.FirmaTeklifs = new HashSet<FirmaTeklif>();
        }
    
        public int FirmaId { get; set; }
        public string FirmaAdi { get; set; }
        public string YetkiliAd { get; set; }
        public string YetkiliSoyad { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public string Telefon { get; set; }
        public Nullable<byte> Sehir { get; set; }
        public string Adres { get; set; }
        public string Fax { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<byte> Puan { get; set; }
        public Nullable<byte> Tip { get; set; }
    
        public virtual Sehir Sehir1 { get; set; }
        public virtual ICollection<FirmaTeklif> FirmaTeklifs { get; set; }
    }
}
