//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaseronBul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ilan
    {
        public Ilan()
        {
            this.FirmaTeklifs = new HashSet<FirmaTeklif>();
        }
    
        public int IlanNo { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<byte> KategoriId { get; set; }
        public Nullable<bool> IlanTuru { get; set; }
        public Nullable<System.DateTime> IlanYayinlamaTarihi { get; set; }
        public Nullable<System.DateTime> IlanKapanisTarihi { get; set; }
        public Nullable<System.DateTime> SonIsGunu { get; set; }
        public Nullable<decimal> MaxFiyat { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string Aciklama { get; set; }
    
        public virtual ICollection<FirmaTeklif> FirmaTeklifs { get; set; }
        public virtual Uye Uye { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
