//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaseronBul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KabulEdilen
    {
        public KabulEdilen()
        {
            this.Bildirims = new HashSet<Bildirim>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TeklifId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual ICollection<Bildirim> Bildirims { get; set; }
        public virtual FirmaTeklif FirmaTeklif { get; set; }
    }
}
