//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaseronBul.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaseronBulEntities1 : DbContext
    {
        public TaseronBulEntities1()
            : base("name=TaseronBulEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bildirim> Bildirims { get; set; }
        public DbSet<Firma> Firmas { get; set; }
        public DbSet<FirmaTeklif> FirmaTeklifs { get; set; }
        public DbSet<Ilan> Ilans { get; set; }
        public DbSet<KabulEdilen> KabulEdilens { get; set; }
        public DbSet<Kategori> Kategoris { get; set; }
        public DbSet<Sehir> Sehirs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Uye> Uyes { get; set; }
        public DbSet<Admin> Admin { get; set; }
    }
}
