//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaseronBul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehir
    {
        public Sehir()
        {
            this.Firmas = new HashSet<Firma>();
            this.Uyes = new HashSet<Uye>();
        }
    
        public byte Plaka { get; set; }
        public string Sehir1 { get; set; }
    
        public virtual ICollection<Firma> Firmas { get; set; }
        public virtual ICollection<Uye> Uyes { get; set; }
    }
}
